---
applications:
- name: usda-fns-ingestor
  stack: cflinuxfs3
  buildpack: python_buildpack
  memory: 512mb
  routes:
    - route: usda-fns-dvs-staging.app.cloud.gov
  instances: 2
  services:
   - usda-fns-ingestor-db